---
id: Rdo
name: Rdo
full: ORM (object relational-mapping) library
description: Rampage Data Objects. Lightweight ORM library.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Rdo
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha5
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/db: ^3
      horde/exception: ^3
      horde/util: ^3
  optional:
    composer:
      horde/test: ^3
