<?php

/**
 * AUTOGENERATED ONLY IF ABSENT
 * Edit this file to match your needs
 * To reset from defaults, run `composer horde:reconfigure --force --mode=proxy`
 */
$deployment_webroot = '/';
$deployment_fileroot = '/home/i567442/php/git/horde/Rdo/web';
$app_fileroot = '/home/i567442/php/git/horde/Rdo/web/horde';
$app_webroot = '/horde';
